bats_timeout := "5"

test-targets *targets="*.bats":
  BATS_TEST_TIMEOUT="{{bats_timeout}}" \
    bats --tap --allow-unix-sockets --filter-tags '!hardware' --jobs {{num_cpus()}} {{targets}}

test-tags *tags:
  BATS_TEST_TIMEOUT="{{bats_timeout}}" \
    bats --tap --allow-unix-sockets --jobs {{num_cpus()}} --filter-tags {{tags}} *.bats

test: (test-targets "*.bats")

test-hardware:
  BATS_TEST_TIMEOUT="30" \
    bats --tap --no-sandbox --filter-tags hardware pivy_ext_interop.bats

test-rust: (test-targets "pivy_agent_rust.bats")

test-conformance: (test-targets "pivy_agent_conformance.bats")

test-conformance-hardware: (test-targets "pivy_agent_conformance_hardware.bats")
